name: inventory_management_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.3.2
  go_router: ^6.2.0
  google_fonts: ^4.0.3
  formz: ^0.7.0
  flutter_dotenv: ^5.0.3
  shared_preferences: ^2.2.2
  flutter_staggered_grid_view: ^0.7.0
  dio: ^5.0.2
  simple_animations: ^5.0.2
  qr_code_scanner: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/loaders/
    - assets/images/
    - assets/images/login/
    - google_fonts/montserrat_alternates/

